package com.ccc.entity;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.score
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.phone
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.score
     *
     * @return the value of test.score
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.score
     *
     * @param score the value for test.score
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public void setScore(String score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.phone
     *
     * @return the value of test.phone
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.phone
     *
     * @param phone the value for test.phone
     *
     * @mbggenerated Tue Jun 09 12:20:38 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}